#use_frameworks!

platform :ios, '8.0'

target 'Segment-Batch_Example' do
  pod 'Segment-Batch', :path => '../'
end

target 'Segment-Batch_Tests' do
  inherit! :search_paths

  pod 'Segment-Batch', :path => '../'
  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock', '~> 3.4'
end